<Workspace Version="1.2.1.3083" X="-106.36160426307" Y="-107.861295395542" zoom="1.55469255719439" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <CoreNodeModels.Watch guid="75e03f13-1650-4b62-baef-f895ed73c0ee" type="CoreNodeModels.Watch" nickname="Watch" x="667.174217542685" y="237.23724547696" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <DSRevitNodesUI.ElementsOfFamilyType guid="89d14e0e-a691-425e-a0e0-de2bcd99f601" type="DSRevitNodesUI.ElementsOfFamilyType" nickname="All Elements of Family Type" x="434.030716752019" y="296.927503573691" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfFamilyType>
    <DSRevitNodesUI.FamilyTypes guid="4fc57a1f-e080-4ded-aa29-300cd1a081a3" type="DSRevitNodesUI.FamilyTypes" nickname="Family Types" x="87.632927866243" y="296.927503573691" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="35:M_Pile Cap-600 Pile:600 x 600 x 900mm" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="89d14e0e-a691-425e-a0e0-de2bcd99f601" start_index="0" end="75e03f13-1650-4b62-baef-f895ed73c0ee" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4fc57a1f-e080-4ded-aa29-300cd1a081a3" start_index="0" end="89d14e0e-a691-425e-a0e0-de2bcd99f601" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="fbaa394c-7960-4feb-9cac-68873497dba3" text="The Revit sample file can be found in Revit's installation directory, typically located in: &#xD;&#xA;&#xD;&#xA;C:\Program Files\Autodesk\Revit 2017\Samples" x="84.9088259540671" y="131.343505208871" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="a887f384-6399-4c78-9d2c-bca2ad041c73" annotationText="Open with Revit file: rac_basic_sample_project.rvt" left="74.9088259540671" top="78.143505208871" width="289.6" height="140.8" fontSize="18" InitialTop="131.343505208871" InitialHeight="140" TextblockHeight="43.2" backgrouund="#FF48B9FF">
      <Models ModelGuid="fbaa394c-7960-4feb-9cac-68873497dba3" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-10.3516321182251" eyeY="13.9155826568604" eyeZ="16.0006294250488" lookX="16.1289100646973" lookY="-8.16507530212402" lookZ="-20.5040168762207" upX="0.0538851283490658" upY="0.996194660663605" upZ="-0.0685019418597221" />
  </Cameras>
</Workspace>